### ISSUE TITLE
Milestone 1: Analysis

### ISSUE THREAD

**Issue by Peeja** [m-ld/web-zero#1]
The goal of the analysis is to maximise the benefit of this project to the software and wider internet
community, and the future utility of the technology m-ld. It will provide a draft specification for the
library code we deliver, including defining a "sustainable app"; requirements with motivating use-
cases; the technical approach taken, including justification of the project hypothesis; and abstract
interface descriptions for application developers and framework developers.

Note that to avoid getting too obtuse, we will not create a "specification specification" here; instead
we will create a draft Sustainable Web Apps specification and iterate and improve it over the
course of the project.

Milestone(s)

• 1.1. Initial Sustainable Web Apps specification document

**Comment by gsvarovsky** [comment]
Specification in progress: https://github.com/m-ld/sustainable-web-apps/tree/analysis/spec

PR: https://github.com/m-ld/sustainable-web-apps/pull/3
